### ISSUE TITLE
Atualizar para .net core 3.1

### ISSUE THREAD

**Issue by eduebrasil** [PampaDevs-BuildingBlocks/PampaDevs.BuildingBlocks#1]
O .net core 2.1 já está em manutenção. Acho que seria interessante atualizar a solução para o .net 3.1 que já é o novo LTS.

**Comment by felipe-allmeida** [comment]
Oi @eduebrasil, acho que você se confundiu .NET Core 2.1 com o .NET Standard 2.1.

O .NET Standard já suporta o .NET Core e vários outros frameworks, tu pode conferir no próprio site da microsoft, aqui: [.NET Standard](https://docs.microsoft.com/pt-br/dotnet/standard/net-standard).

**Comment by eduebrasil** [comment]
Verdade. Valeu
